on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      repo:
        required: true
        type: string
      dockerhub_repo:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  feature-branch:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read  # <--- Adding this often fixes the "not accessible" error
      contents: read
    steps:
      - run: |
          echo "${{ inputs.branch }}"

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Read version file from current feature branch
        id: get_version
        run: |
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      
      - name: Get short git SHA
        id: get_sha
        run: |
          # Extracts the first 7 characters of the SHA
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Docker tags for feature branch
        id: set_image_tag
        run: |
          echo "docker_image_tag=${{ steps.get_version.outputs.version }}-${{ steps.get_sha.outputs.sha_short }}" >> $GITHUB_OUTPUT
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.30.1
          platforms: linux/arm64
          use: true
          cleanup: true
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: true
          tags: "${{ inputs.dockerhub_repo }}/${{ inputs.repo }}:${{ steps.set_image_tag.outputs.docker_image_tag }}"
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ inputs.dockerhub_repo }}/${{ inputs.repo }}:${{ steps.set_image_tag.outputs.docker_image_tag }}"
          # exit-code: '1'
          # ignore-unfixed: true
          # vuln-type: 'os,library'
          # severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
